### ISSUE TITLE
Problemas na importação de bibliotecas externas

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua-node#7]

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Favor detalhar exemplo de simulação do problema.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Testar seguinte cenário:

Depois de instalar `moment` global.
```
var m = importar('moment')
escreva(m)
```

erros:
> [Linha: undefined] Erro em JavaScript: undefined
> Pilha de execução: undefined

**Comment by leonelsanchesdasilva** [comment]
Adicionada uma mensagem de erro melhor quanto pacote está faltando, a partir da versão 0.17.4.
